### ISSUE TITLE
File Loading Error. Please Verify Game Files

### ISSUE THREAD

**Issue by autobiografia** [moffel1020/BrawlhallaSwz.CLI#1]
I need help because I can't put changed files in the game without the message showing that the game files are damaged. Does anyone have an idea on how to make this work correctly? Because if not, there's no point encrypting it again without it working in the game.

File Loading Error. Please Verify Game Files

**Comment by moffel1020** [comment]
This can happen if you are saving edited xml files with CRLF line endings instead of LF line endings. The xml parser brawlhalla uses requires line endings to be LF, so make sure you select this in your editor when making changes.

**Comment by autobiografia** [comment]
> This can happen if you are saving edited xml files with CRLF line endings instead of LF line endings. The xml parser brawlhalla uses requires line endings to be LF, so make sure you select this in your editor when making changes.

It's a CSV that I was trying to modify (Sorry for not mentioning this before, I ended up forgetting). I was able to edit an XML and it opened the game, but unfortunately it left me without a connection to the network. Do you know how to resolve this?

**Comment by moffel1020** [comment]
Unfortunately it is not possible to launch the game in online mode with modded swz files on disk. Technically it would possible by injecting the data at runtime via the RawData dll, however I do not recommend trying this because your client can get desynced from the server and you will get banned

As for csv reading issues, it really depends on what you are trying to modify. The game does some checks to see if the files are in the correct format. Sometimes it logs useful info about the error to a file. You can view these logs by using the ```-diagnosticlog``` [launch option](https://brawlhalla.wiki.gg/wiki/Launch_options#-diagnosticlog/-diagnosticslog). This can help you find out what method in BrawlhallaAir.swf caused the error.
